TRADUCCIONES = {
    "es": {
        # nav / footer
        "reservar": "Reservar",
        "ver_detalles": "Ver equipamiento y normas de la casa",
        "reservas": "Reservas",
        "galeria": "Galería",
        "guia": "Guía",
        "ubicacion": "Ubicación",
        "footer_pago": "Reservas por WhatsApp, Instagram y email.",
        # hero
        "reservar_estadia": "Reservar estadía",
        "conocer_casas": "Conocer las casas",
        # intro
        "la_idea": "La idea",
        "intro_titulo": "Una casa que cumplió cien años, en el mismo valle de siempre.",
        "intro_texto": "La Casa Centenario lleva alrededor de un siglo de pie en este terreno: sus muros han visto pasar generaciones enteras. Se restauró para alojar sin perder lo que la hace vieja en el buen sentido.",
        # experiencias
        "que_encontrar": "Qué encontrar",
        "que_encontrar_sub": "Pensado para desconectarse de verdad",
        # servicios
        "servicios_extra": "Servicios extra",
        "servicios_titulo": "Para hacer la estadía aún mejor",
        "servicios_sub": "Disponibles en ambas casas. Se eligen al momento de reservar.",
        # reserva
        "reservas_contacto": "Reservas y contacto",
        "cuentanos": "Cuéntanos para cuándo",
        "reserva_lead": "Completa el formulario y te escribimos por WhatsApp para confirmar. También puedes escribirnos directo.",
        "solicitar_reserva": "Solicitar reserva",
        "disponibilidad": "Disponibilidad",
        "enviar_solicitud": "Enviar solicitud por WhatsApp",
        "casa": "Casa",
        "llegada": "Llegada",
        "salida": "Salida",
        "huespedes": "Huéspedes",
        "nombre": "Nombre",
        "contacto": "Teléfono",
        "mensaje": "Mensaje",
        # ubicacion
        "como_llegar": "Lugares de interés",
        # galeria
        "galeria_titulo": "La zona, en imágenes",
        "galeria_lead": "Un vistazo al valle, los cerros y el entorno alrededor de las casas.",
        # guia
        "guia_titulo": "Qué hacer en la zona",
        "guia_lead": "Atractivos cerca de las casas, en el valle del Huasco y sus alrededores.",
        "descargar_pdf": "Descargar guía en PDF",
        "ubicacion_titulo": "Lugares cercanos a nosotros.",
        "ubicacion_texto": "Conoce los sitios de interés que estan en nuestro valle.",
        "cielo_k": "CIELO", "cielo_titulo": "Noches sin luz de ciudad",
        "cielo_texto": "El cielo del valle del Huasco, lejos del ruido de Vallenar, se presta para observar estrellas sin instrumentos.",
        "silencio_k": "SILENCIO", "silencio_titulo": "Un lugar realmente tranquilo",
        "silencio_texto": "Sin tráfico ni aglomeración: el ritmo lo pone el valle, no el reloj.",
        "acceso_k": "ACCESO", "acceso_titulo": "Cerca, pero afuera",
        "ahora_en_zona": "Ahora en la zona",
        "desierto_promo_sub": "Descubre los distintos lugares de nuestro valle del Huasco.",
        "ver_guia_completa": "Ver guía completa →",
        "acceso_texto": "Camino fácil, sin perder la sensación de estar en otro lugar.",
        "antes_de_ir": "Antes de ir",
        "tips_titulo": "Visita el desierto florido con cuidado",
        "tip_1": "No arranques ni pises las flores.",
        "tip_2": "No ingreses con vehículos a zonas de floración, dunas o playas.",
        "tip_3": "Llévate toda tu basura de vuelta.",
        "visitar_sitio": "Visitar sitio web",
        "descubre_zona": "Descubre la zona",
        "email": "Email",
        "lo_que_dicen": "Lo que dicen nuestros huéspedes",
        "resenas_sub": "Experiencias reales de quienes ya se alojaron con nosotros.",
        "ver_todas_resenas": "Ver todas las reseñas",
        "resenas_nav": "Reseñas",
        "guia": "La Zona",
        "guia_titulo": "Puntos de interés cerca de las casas",
        "guia_lead": "Desierto florido, viñas, transporte y más — todo ubicado en el mapa.",
                
    },  
    "en": {
        "reservar": "Book",
        "reservas": "Booking",
        "galeria": "Gallery",
        "guia": "Guide",
        "ubicacion": "Location",
        "footer_pago": "Book via WhatsApp, Instagram or email.",
        "reservar_estadia": "Book your stay",
        "conocer_casas": "See the houses",
        "la_idea": "The idea",
        "intro_titulo": "A house that turned one hundred, in the same valley as always.",
        "intro_texto": "Casa Centenario has stood on this land for roughly a century: its walls have seen entire generations go by. It was restored to host guests without losing what makes it beautifully old.",
        "que_encontrar": "What you'll find",
        "que_encontrar_sub": "Made for real disconnection",
        "servicios_extra": "Extra services",
        "servicios_titulo": "To make your stay even better",
        "servicios_sub": "Available at both houses. Choose them when you book.",
        "reservas_contacto": "Booking & contact",
        "cuentanos": "Tell us your dates",
        "reserva_lead": "Fill out the form and we'll message you on WhatsApp to confirm. You can also reach us directly.",
        "solicitar_reserva": "Request booking",
        "disponibilidad": "Availability",
        "enviar_solicitud": "Send request via WhatsApp",
        "casa": "House",
        "llegada": "Check-in",
        "salida": "Check-out",
        "huespedes": "Guests",
        "nombre": "Name",
        "ahora_en_zona": "Happening now",
        "desierto_promo_sub": "Discover the different spots where you can see our Huasco Valley.",
        "ver_guia_completa": "See full guide →",
        "contacto": "Phone number",
        "mensaje": "Message",
        "como_llegar": "How to get here",
        "galeria_titulo": "The area, in pictures",
        "galeria_lead": "A look at the valley, the hills, and the surroundings of the houses.",
        "guia_titulo": "What to do nearby",
        "guia_lead": "Attractions close to the houses, in the Huasco valley and around.",
        "descargar_pdf": "Download PDF guide",
        "ver_detalles": "See house amenities & house rules",
        "ubicacion_titulo": "15 km from Vallenar, in the Huasco valley.",
        "ubicacion_texto": "A quiet, easy-to-reach spot: close enough to town to get here without hassle, far enough to leave the noise behind. Atacama is known for its clear skies, perfect for disconnecting under the stars.",
        "cielo_k": "SKY", "cielo_titulo": "Nights with no city lights",
        "cielo_texto": "The sky over the Huasco valley, away from Vallenar's lights, is perfect for stargazing with no equipment needed.",
        "silencio_k": "QUIET", "silencio_titulo": "A truly peaceful place",
        "silencio_texto": "No traffic, no crowds — the valley sets the pace, not the clock.",
        "acceso_k": "ACCESS", "acceso_titulo": "Close, yet away from it all",
        "acceso_texto": "Easy road access, without losing the feeling of being somewhere else.",
        "antes_de_ir": "Before you go",
        "tips_titulo": "Visit the flowering desert responsibly",
        "tip_1": "Don't pick or step on the flowers.",
        "tip_2": "Don't drive into blooming areas, dunes, or beaches.",
        "tip_3": "Take all your trash back with you.",
        "visitar_sitio": "Visit website",
        "descubre_zona": "Discover the area",
        "email": "Email",
        "lo_que_dicen": "What our guests say",
        "resenas_sub": "Real experiences from people who've stayed with us.",
        "ver_todas_resenas": "See all reviews",
        "resenas_nav": "Reviews",
        "guia": "The Area",
        "guia_titulo": "Points of interest near the houses",
        "guia_lead": "Flowering desert, wineries, transport and more — all located on the map.",
                
    },
}


def idioma(request):
    lang = request.session.get("idioma", "es")
    return {
        "t": TRADUCCIONES.get(lang, TRADUCCIONES["es"]),
        "idioma_actual": lang,
    }