# Generated by Django 6.0.7 on 2026-07-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('centenario', 'Casa Centenario'), ('moderna', 'Casa Moderna')], max_length=20, unique=True, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre a mostrar')),
                ('eyebrow', models.CharField(max_length=60, verbose_name='Texto pequeño superior')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('antiguedad_texto', models.CharField(blank=True, max_length=60, verbose_name='Antigüedad')),
                ('capacidad_huespedes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad de huéspedes')),
                ('precio_desde', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio desde (CLP)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('activa', models.BooleanField(default=True, verbose_name='Visible en la página')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='casas/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=80, verbose_name='Descripción breve')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cabanas.casa')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
