# Generated by Django 6.0.7 on 2026-07-29 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('contacto', models.CharField(max_length=100, verbose_name='Teléfono o email')),
                ('fecha_llegada', models.DateField(blank=True, null=True, verbose_name='Llegada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Salida')),
                ('huespedes', models.PositiveIntegerField(default=2, verbose_name='Huéspedes')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje adicional')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmar'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='cabanas.casa')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
