# Generated by Django 6.0.7 on 2026-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Entresiglos', max_length=60, verbose_name='Nombre de marca')),
                ('brand_subtitle', models.CharField(default='Casas de campo en el Huasco', max_length=120, verbose_name='Subtítulo')),
                ('whatsapp_number', models.CharField(help_text="Sin '+' ni espacios. Ej: 56912345678", max_length=20, verbose_name='WhatsApp')),
                ('instagram_handle', models.CharField(help_text='Con @. Ej: @entresiglos.huasco', max_length=40, verbose_name='Instagram')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('maps_embed_url', models.URLField(blank=True, verbose_name='URL de Google Maps (embed)')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
