# Generated by Django 6.0.7 on 2026-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0003_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='distancia_a_vallenar_km',
            field=models.PositiveIntegerField(default=10, verbose_name='Distancia a Vallenar (km)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitulo',
            field=models.CharField(default='A 10 km de Vallenar, un lugar tranquilo y de fácil acceso en el valle del Huasco.', max_length=200, verbose_name='Subtítulo del hero'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_titulo',
            field=models.TextField(default='Casa Centenario<br><em>cien años de historia</em>', help_text='Puedes usar <br> para salto de línea y <em>...</em> para cursiva.', verbose_name='Título del hero'),
        ),
    ]
