# Generated by Django 6.0.7 on 2026-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0004_casa_distancia_a_vallenar_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='zona/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=80, verbose_name='Descripción breve')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Foto de la zona',
                'verbose_name_plural': 'Galería de la zona',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio (CLP)')),
                ('icono', models.CharField(blank=True, help_text='Ej: 🛁 para tinaja, ☕ para desayuno. Opcional.', max_length=10, verbose_name='Ícono (emoji)')),
                ('activo', models.BooleanField(default=True, verbose_name='Disponible')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(blank=True, to='cabanas.servicio', verbose_name='Servicios extra'),
        ),
    ]
