# Generated by Django 6.0.7 on 2026-07-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0005_fotozona_servicio_reserva_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen de fondo'),
        ),
    ]
