# Generated by Django 6.0.7 on 2026-07-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0006_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('desierto_florido', 'Desierto Florido'), ('mirador', 'Mirador'), ('pueblo', 'Pueblo / cultura'), ('aire_libre', 'Aire libre'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('distancia_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distancia (km)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='atractivos/', verbose_name='Imagen')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece primero y más grande en la página de guía.', verbose_name='Destacado')),
                ('temporada_inicio', models.DateField(blank=True, help_text='Solo para atractivos estacionales, ej. Desierto Florido. Déjalo vacío si no aplica.', null=True, verbose_name='Temporada — inicio')),
                ('temporada_fin', models.DateField(blank=True, null=True, verbose_name='Temporada — fin')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Atractivo turístico',
                'verbose_name_plural': 'Guía — Atractivos turísticos',
                'ordering': ['-destacado', 'orden', 'id'],
            },
        ),
    ]
