# Generated by Django 6.0.7 on 2026-07-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0007_atractivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='guia_pdf',
            field=models.FileField(blank=True, help_text='Sube un PDF descargable con recomendaciones de la zona.', null=True, upload_to='guias/', verbose_name='Guía turística (PDF)'),
        ),
    ]
