# Generated by Django 6.0.7 on 2026-08-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0008_siteconfig_guia_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Opcional.', verbose_name='Descripción (inglés)'),
        ),
    ]
