# Generated by Django 6.0.7 on 2026-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0009_casa_descripcion_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='atractivo',
            name='descripcion_en',
            field=models.TextField(blank=True, verbose_name='Descripción (inglés)'),
        ),
        migrations.AddField(
            model_name='atractivo',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre (inglés)'),
        ),
        migrations.AddField(
            model_name='casa',
            name='eyebrow_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Texto pequeño superior (inglés)'),
        ),
        migrations.AddField(
            model_name='casa',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre (inglés)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_en',
            field=models.TextField(blank=True, verbose_name='Descripción (inglés)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nombre (inglés)'),
        ),
    ]
