# Generated by Django 6.0.7 on 2026-08-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0010_atractivo_descripcion_en_atractivo_nombre_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitulo_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtítulo del hero (inglés)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_titulo_en',
            field=models.TextField(blank=True, verbose_name='Título del hero (inglés)'),
        ),
    ]
