# Generated by Django 6.0.7 on 2026-08-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0011_siteconfig_hero_subtitulo_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='acepta_mascotas',
            field=models.BooleanField(default=False, verbose_name='Acepta mascotas'),
        ),
        migrations.AddField(
            model_name='casa',
            name='checkin_hora',
            field=models.CharField(blank=True, help_text='Ej: 15:00', max_length=20, verbose_name='Check-in desde'),
        ),
        migrations.AddField(
            model_name='casa',
            name='checkout_hora',
            field=models.CharField(blank=True, help_text='Ej: 11:00', max_length=20, verbose_name='Check-out hasta'),
        ),
        migrations.AddField(
            model_name='casa',
            name='reglas_texto',
            field=models.TextField(blank=True, help_text='Una regla por línea. Ej: No fiestas ni eventos.', verbose_name='Reglas adicionales'),
        ),
        migrations.AddField(
            model_name='casa',
            name='reglas_texto_en',
            field=models.TextField(blank=True, verbose_name='Reglas adicionales (inglés)'),
        ),
        migrations.CreateModel(
            name='AmenidadCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(blank=True, help_text='Ej: 🔥 🚿 📺 💧', max_length=10, verbose_name='Ícono (emoji)')),
                ('texto', models.CharField(max_length=60, verbose_name='Texto')),
                ('texto_en', models.CharField(blank=True, max_length=60, verbose_name='Texto (inglés)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidades', to='cabanas.casa', verbose_name='Casa')),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
