# Generated by Django 6.0.7 on 2026-08-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0012_casa_acepta_mascotas_casa_checkin_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atractivo',
            name='categoria',
            field=models.CharField(choices=[('desierto_florido', 'Desierto Florido'), ('vinas', 'Viñas y bodegas'), ('cabalgatas', 'Tours y actividades'), ('mirador', 'Mirador'), ('pueblo', 'Pueblo / cultura'), ('aire_libre', 'Aire libre'), ('costa', 'Caleta / Costa'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
    ]
