# Generated by Django 6.0.7 on 2026-08-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0013_alter_atractivo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atractivo',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='Opcional. Ej: https://www.pagina.cl', verbose_name='Sitio web'),
        ),
    ]
