# Generated by Django 6.0.7 on 2026-08-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0014_atractivo_sitio_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='atractivo',
            name='mostrar_en_banner',
            field=models.BooleanField(default=False, help_text='Actívalo para que la foto de este atractivo aparezca en el carrusel de la página principal.', verbose_name='Mostrar en banner del inicio'),
        ),
    ]
