# Generated by Django 6.0.7 on 2026-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0015_atractivo_mostrar_en_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, help_text='Para enviar la confirmación por correo.', max_length=254, verbose_name='Email'),
        ),
    ]
