# Generated by Django 6.0.7 on 2026-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0016_reserva_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_pais',
            field=models.CharField(default='+56', max_length=5, verbose_name='Código de país'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='contacto',
            field=models.CharField(max_length=100, verbose_name='Teléfono'),
        ),
    ]
