# Generated by Django 6.0.7 on 2026-08-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0017_reserva_codigo_pais_alter_reserva_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=80, verbose_name='Nombre del huésped')),
                ('estrellas', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Estrellas')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('texto_en', models.TextField(blank=True, verbose_name='Comentario (inglés)')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de la estadía')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='cabanas.casa')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['orden', '-fecha', 'id'],
            },
        ),
    ]
