# Generated by Django 6.0.7 on 2026-08-14 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0018_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resena', to='cabanas.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='resena_solicitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token_resena',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='resena',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
    ]
