# Generated by Django 6.0.7 on 2026-08-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0019_resena_reserva_reserva_resena_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atractivo',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='atractivo',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='atractivo',
            name='categoria',
            field=models.CharField(choices=[('desierto_florido', 'Desierto Florido'), ('vinas', 'Viñas y bodegas'), ('cabalgatas', 'Tours y actividades'), ('transporte', 'Transporte'), ('mirador', 'Mirador'), ('pueblo', 'Pueblo / cultura'), ('aire_libre', 'Aire libre'), ('costa', 'Caleta / Costa'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
    ]
