# Generated by Django 6.0.7 on 2026-08-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0020_atractivo_latitud_atractivo_longitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud de la casa'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud de la casa'),
        ),
    ]
