# Generated by Django 6.0.7 on 2026-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0021_siteconfig_latitud_siteconfig_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('nombre_en', models.CharField(blank=True, max_length=80, verbose_name='Nombre (inglés)')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Punto de interés (mapa)',
                'verbose_name_plural': 'Mapa — Puntos de interés',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
