# Generated by Django 6.0.7 on 2026-09-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0022_puntomapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicios_dias',
            field=models.JSONField(blank=True, default=dict, verbose_name='Días por servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='cobro_por_noche',
            field=models.BooleanField(default=False, help_text='Si está activo, el huésped elige cuántas noches lo quiere.', verbose_name='Se cobra por noche'),
        ),
    ]
