# Generated by Django 6.0.7 on 2026-10-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabanas', '0023_reserva_servicios_dias_servicio_cobro_por_noche'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='ical_ultima_sync',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='ical_url',
            field=models.URLField(blank=True, help_text='Airbnb → Calendario → Conectar calendarios → Exportar calendario', max_length=500, verbose_name='Enlace iCal de Airbnb'),
        ),
        migrations.CreateModel(
            name='BloqueoFechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(verbose_name='Desde (llegada)')),
                ('fecha_hasta', models.DateField(verbose_name='Hasta (salida)')),
                ('motivo', models.CharField(blank=True, max_length=100, verbose_name='Motivo')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('airbnb', 'Airbnb')], default='manual', max_length=10, verbose_name='Origen')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='cabanas.casa')),
            ],
            options={
                'verbose_name': 'Bloqueo de fechas',
                'verbose_name_plural': 'Bloqueos de fechas',
                'ordering': ['fecha_desde'],
            },
        ),
    ]
